### ISSUE TITLE
Unfortunately PDFViewer has stopped

### ISSUE THREAD

**Issue by Xxxxyyy** [ieee8023/PDFViewer#9]
942-1277/? E/AndroidRuntime﹕ FATAL EXCEPTION: ThumbnailLoader-2
    Process: the.pdfviewerx, PID: 942
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at org.emdev.ui.tasks.AsyncTask$2.done(AsyncTask.java:230)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     **Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.Void[]
            at **org.ebookdroid.common.cache.ThumbnailFile$LoadingTask.doInBackground(ThumbnailFile.java:164)
            at org.emdev.ui.tasks.AsyncTask$1.call(AsyncTask.java:215)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)****

**Comment by chuaandy881** [comment]
On issue

**Comment by chuaandy881** [comment]
2018

**Comment by CrisAdam-VeasnaKhy** [comment]
Dino Morea the road to the road to[Khyveasna](khyveasna111@gmail.com)
